### ISSUE TITLE
Buffer limit error

### ISSUE THREAD

**Issue by fiveseven808** [hblasins/OlympusAir#2]
I try to run the preview.py as well as the captureScript.py and I receive the following:

> ======= ./2019-01-21_16-50-08 =======
> Establishing liveview socket 65001: OK
> Camera live view resolution change to 0320x0240: OK
> Camera live view start: OK
> Traceback (most recent call last):
>   File ".\captureScript.py", line 29, in <module>
>     cam.startPreview()
>   File "C:\Users\yoshf\OneDrive\Desktop\OlympusAir-master\olympusair\OlympusAir.py", line 765, in startPreview
>     data = self.lvSocket.recvfrom(128)
> socket.error: [Errno 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself

**Comment by fiveseven808** [comment]
Additional details: This error was on a windows 10 machine. 

When I ran this on a pi, I did not recieve this error, but I also was not able to see the live view. I would like to know what CV2 package the author used so I can replicate funtionality.

**Comment by hblasins** [comment]
If I remember correctly I tried it with opencv 2.x.
